export const dataCheckboxes = {
    id: 'brandFilter',
    name: 'brand',
    options: [
        {
            id: 'filter-1',
            isChecked: true,
            isDisabled: false,
            label: 'Apple',
            labelTypography: 'paragraph-default',
            value: 'Apple',
        },
        {
            id: 'filter-2',
            isChecked: true,
            isDisabled: false,
            label: 'Samsung',
            labelTypography: 'paragraph-default',
            value: 'Samsung',
        },
        {
            id: 'filter-3',
            isChecked: false,
            isDisabled: false,
            label: 'Google',
            labelTypography: 'paragraph-default',
            value: 'Google',
        },
        {
            id: 'filter-4',
            isChecked: false,
            isDisabled: false,
            label: 'Motorola',
            labelTypography: 'paragraph-default',
            value: 'Motorola',
        },
        {
            id: 'filter-5',
            isChecked: false,
            isDisabled: false,
            label: 'TLC',
            labelTypography: 'paragraph-default',
            value: 'TLC',
        },
        {
            id: 'filter-6',
            isChecked: false,
            isDisabled: false,
            label: 'LG',
            labelTypography: 'paragraph-default',
            value: 'LG',
        },
        {
            id: 'filter-7',
            isChecked: false,
            isDisabled: true,
            label: 'Alcatel',
            labelTypography: 'paragraph-default',
            value: 'Alcatel',
        },
    ],
};

export const dataCheckboxesMoreThanEight = {
    id: 'colorFilter',
    name: 'color',
    options: [
        {
            id: 'filter-1',
            isChecked: false,
            isDisabled: false,
            label: 'Black',
            labelTypography: 'paragraph-default',
            value: 'Black',
        },
        {
            id: 'filter-2',
            isChecked: false,
            isDisabled: false,
            label: 'White',
            labelTypography: 'paragraph-default',
            value: 'White',
        },
        {
            id: 'filter-3',
            isChecked: false,
            isDisabled: false,
            label: 'Blue',
            labelTypography: 'paragraph-default',
            value: 'Blue',
        },
        {
            id: 'filter-4',
            isChecked: false,
            isDisabled: false,
            label: 'Grey',
            labelTypography: 'paragraph-default',
            value: 'Grey',
        },
        {
            id: 'filter-5',
            isChecked: false,
            isDisabled: false,
            label: 'Gold',
            labelTypography: 'paragraph-default',
            value: 'Gold',
        },
        {
            id: 'filter-6',
            isChecked: false,
            isDisabled: true,
            label: 'Red',
            labelTypography: 'paragraph-default',
            value: 'Red',
        },
        {
            id: 'filter-7',
            isChecked: false,
            isDisabled: false,
            label: 'Yellow',
            labelTypography: 'paragraph-default',
            value: 'Yellow',
        },
        {
            id: 'filter-8',
            isChecked: false,
            isDisabled: true,
            label: 'Pink',
            labelTypography: 'paragraph-default',
            value: 'Pink',
        },
        {
            id: 'filter-9',
            isChecked: false,
            isDisabled: true,
            label: 'Orange',
            labelTypography: 'paragraph-default',
            value: 'Orange',
        },
        {
            id: 'filter-10',
            isChecked: false,
            isDisabled: false,
            label: 'Green',
            labelTypography: 'paragraph-default',
            value: 'Green',
        },
        {
            id: 'filter-11',
            isChecked: false,
            isDisabled: false,
            label: 'Purple',
            labelTypography: 'paragraph-default',
            value: 'Purple',
        },
        {
            id: 'filter-12',
            isChecked: false,
            isDisabled: true,
            label: 'Pale blue',
            labelTypography: 'paragraph-default',
            value: 'Pale blue',
        },
    ],
};

export const dataSlider = {
    max: {
        description: '$999/month',
        inputId: 'inputIdMax',
        legend: 'Maximum',
        value: '999',
    },
    min: {
        description: '$0/month',
        inputId: 'inputIdMin',
        legend: 'Minimum',
        value: '0',
    },
    minimumGap: 20,
    step: '1',
    unitLabel: '$',
    unitPosition: 'start',
    value: ['0', '999'],
};
