

export const interfaceIcons = [
    {
        category: 'Common controls',
        list: [
            'cancel',
            'out',
            'hourglass',
            'edit',
            'bin',
            'lock',
            'menu-burger',
            'menu-option',
            'repeat',
            'search',
            'settings',
            'eye-dash',
            'eye',
        ]
    },
    {
        category: 'Arrows and chevrons',
        list: [
            'chevron-down',
            'chevron-left',
            'chevron-right',
            'chevron-up',
            'dot',
            'interpunct',
            'order-asc',
            'order-desc',
            'order-none',
        ]
    },
    {
        category: 'Add and remove',
        list: [
            'x',
            'checkmark',
            'plus',
            'minus',
            'checkmark-circle',
            'x-circle--fill-color',
            'plus-circle-fill-color',
            'minus-circle-fill-color',
            'checkmark-circle-fill-color',
        ]
    },
    {
        category: 'Attention',
        list: [
            'question-circle',
            'exclamation-circle',
            'information-circle',
            'exclamation-circle-fill-color',
            'information-circle-fill-color',
            'question-circle-small',
            'exclamation-circle-fill-color-small24',
            'information-circle-fill-color-small24',
        ]
    },
    {
        category: 'Links and medias',
        list: [
            'camera',
            'external-link',
            'file-pdf',
            'link',
        ]
    },
    {
        category: 'Rating',
        list: [
            'star-empty',
            'star-full',
            'star-half',
        ]
    },
    {
        category: 'Communication',
        list: [
            'actualite',
            'communaute',
            'email',
            'voice-command',
            'call-incoming',
            'call',
            'mobile-livechat',
            'chat',
        ]
    },
    {
        category: 'Time and place',
        list: [
            'clock',
            'calendar',
            'pin',
        ]
    },
    {
        category: 'Users',
        list: [
            'profile',
            'user-family',
            'user',
        ]
    },
    {
        category: 'Download and upload',
        list: [
            'download',
            'upload',
            'circle-download',
            'circle-upload',
        ]
    },
    {
        category: 'Social medias',
        list: [
            'facebook',
            'instagram',
            'youtube',
            'twitter',
        ]
    },
    {
        category: 'Cast and devices',
        list: [
            'appli-helix',
            'helix-tv',
            'relais-wifi',
            'mobile',
            'television',
        ]
    },
    {
        category: 'Account',
        list: [
            'account-balance',
            'installation',
            'support',
            'cart',
            'hierarchy',
        ]
    },
    {
        category: 'TV Plans',
        list: [
            'forfait-tv-fan-sports',
            'forfait-tv-la-decouverte',
            'forfait-tv-la-totale',
            'forfait-tv-le-fan-de-films-et-series',
            'forfait-tv-le-plein-la-vue',
            'forfait-tv-streaming',
        ]
    },
    {
        category: 'Services et options',
        list: [
            'helix-app',
            'tv-4k',
            'tv-forward',
            'tv-record',
            'casting',
            'cloud-dvr',
            'unlimited',
            'parental-control',
            'wifi',
            'world',
            'play-circle',
        ]
    },
    {
        category: 'Internet plans - options',
        list: [
            'helixinternet-jeuxvideos',
            'helixinternet-maison-connecte',
            'helixinternet-musique',
            'helixinternet-streaming',
            'helixinternet-wifi_ultime',
        ]
    },
];

export const illustrationIcons = [
    {
        category: 'Main',
        list: [
            'accessibilite',
            'actualite',
            'agilite',
            'apple',
            'appli-helix-tv',
            'application-espace-client',
            'applications',
            'bac-recyclage',
            'boite-usage',
            'calendrier',
            'call-me-back',
            'call-me-now',
            'canada',
            'checklist',
            'chrono',
            'clavardage',
            'coche',
            'communaute',
            'contact-phone',
            'courriels',
            'couverture-reseau-cdn',
            'couverture-reseau',
            'demenagement',
            'depannage',
            'desinstallation',
            'differenciation',
            'disponibilite-du-service',
            'domotique',
            'donnees',
            'etats-unis',
            'facture-delais-48h',
            'facture',
            'hebergement-donnees',
            'hebergement',
            'helix-accessibilite-notifications',
            'helix-accessibilite-parametres',
            'helix-micro',
            'information',
            'innovation',
            'installation',
            'instructions',
            'international',
            'jouer',
            'livraison',
            'magasin-videotron',
            'mettre-a-jour',
            'mon-compte',
            'nouveau-client',
            'paiement-preautorise',
            'panier-achat',
            'pause',
            'perf-reseau-reconnue',
            'performance',
            'point-de-vente',
            'quebec',
            'question',
            'recherche',
            'rejouer',
            'rnregistrements-simultanes',
            'service-clientele',
            'son-active',
            'son-muet',
            'temps',
            'travai-equipe',
            'trio-wifi',
            'usagers-duo',
            'usagers-quatuor',
            'usagers-solo',
            'usagers-trio',
            'verifier-admissibilite',
            'videotron-affaires',
            'videotron-plus',
            'voyage',
            'wifi',
        ]
    },
        {
        category: 'Options',
        list: [
            'casting',
            'cloud-dvr',
            'connexion-fiable',
            'garantie-30-jours',
            'illimites',
            'memoire',
            'rabais-etudiant',
            'securite-bienveillant',
            'sous-titres',
            'video-qualite-4K',
            'video-qualite-720p',
            'video-qualite-1080p',
            'vitesse-envoi',
            'vitesse-telechargement',
        ]
    },
    {
        category: 'Options Mobility',
        list: [
            'appareil-photo',
            'batterie',
            'messagerie-vocale-courriel',
            'messagerie-vocale',
            'mobile-afficheur',
            'mobile-appel-attente',
            'mobile-appels-internationaux',
            'mobile-conf-telephonique',
            'mobile-economie-argent',
            'mobile-flex-cell',
            'mobile-grand-format-compact',
            'mobile-illimite',
            'mobile-messagerie-vocale-visuelle',
            'mobile-multilignes',
            'mobile-planif-appel',
            'mobile-protection',
            'mobile-regr-forfaits',
            'mobile-renvoi-appel',
            'option-tout-inclus',
            'resistance-eau',
            'taille-ecran',
        ]
    },
    {
        category: 'Navigation',
        list: [
            'agrandir',
            'arrow-bas',
            'arrow-droite',
            'arrow-fermer',
            'arrow-gauche',
            'arrow-haut',
            'arrow-plus',
            'checkmark',
            'reduire',
        ]
    },
    {
        category: 'Devices',
        list: [
            'appareils-pod',
            'appareils',
            'autres-services',
            'borne-helix-1',
            'borne-helix-2',
            'borne-helix-et-relais',
            'carte-memoire',
            'carte-sim',
            'helix-tv-remote',
            'helix-tv',
            'internet-residentiel',
            'laptop-mobile',
            'mobilite',
            'multi-produit',
            'pod-relais-vue-1',
            'pod-relais-vue-2',
            'pod-relais-vue-3',
            'tablette-mobile-helix',
            'telecommande',
            'telephonie',
            'television',
            'terminal-telecommande',
            'terminal-top',
            'terminal',
        ]
    },
    {
        category: 'Forfait',
        list: [
            'forfait-la-decouverte',
            'forfait-la-totale',
            'forfait-le -plein-la-vue',
            'forfait-le-fan-de-films-et-series',
            'forfait-le-fan-de-sports',
            'forfait-le-leger',
        ]
    }
];

export const iconsPL = [
    // '_icon-font-awesome-stack',
    // '_icon-font-awesome',
    'arrow-to-bottom',
    'arrow-to-right--breadcrumb',
    'arrow-to-right',
    'arrow-to-top',
    'bullet-rating',
    'step-number',
    'svg-accessibility',
    'svg-app-store-fr',
    'svg-application-helix-stream',
    'svg-application-helix',
    'svg-arrow-circle-left',
    'svg-arrow-circle-right',
    'svg-arrow-sort-asc',
    'svg-arrow-sort-desc',
    'svg-arrow-sort',
    'svg-attention',
    'svg-boundary',
    'svg-business',
    'svg-calendar',
    'svg-call',
    'svg-cart-mini',
    'svg-cart',
    'svg-check-eligibility',
    'svg-checkbox-selected',
    'svg-checkmark-circle',
    'svg-checkmark',
    'svg-clock',
    'svg-cloud-dvr',
    'svg-collapse-trigger-arrow-down',
    'svg-collapse-trigger-arrow-up',
    'svg-device',
    'svg-download',
    'svg-edit',
    'svg-equipment',
    'svg-error',
    'svg-external-link',
    'svg-eye-dashed',
    'svg-eye',
    'svg-family',
    'svg-file-billing',
    'svg-filter',
    'svg-gateway',
    'svg-google-store-fr',
    'svg-handheld',
    'svg-handshake',
    'svg-helix-tv-app',
    'svg-helix-tv',
    'svg-helix',
    'svg-important',
    'svg-installation',
    'svg-internet',
    'svg-interrogation',
    'svg-letter',
    'svg-lightbulb',
    'svg-lock',
    'svg-logo-videotron',
    'svg-manage',
    'svg-mastercard',
    'svg-minus-bold',
    'svg-minus-circle',
    'svg-minus',
    'svg-move',
    'svg-other-services',
    'svg-parental-control',
    'svg-pdf',
    'svg-person',
    'svg-pin',
    'svg-plus-bold',
    'svg-plus-circle',
    'svg-plus',
    'svg-pod',
    'svg-reset',
    'svg-search',
    'svg-social',
    'svg-support',
    'svg-terminal-handheld',
    'svg-terminal',
    'svg-tpc',
    'svg-trash',
    'svg-travel',
    'svg-truck',
    'svg-tv',
    'svg-uninstallation',
    'svg-unlimited',
    'svg-upload',
    'svg-user-profile',
    'svg-video-play',
    'svg-voice-command',
    'svg-wifi',
    'svg-x',
    // 'svg',
];