

export const interfaceIcons = [
    {
        category: 'Common controls',
        list: [
            'cancel',
            'out',
            'hourglass',
            'edit',
            'bin',
            'lock',
            'menu-burger',
            'menu-option',
            'repeat',
            'search',
            'settings',
            'eye-dash',
            'eye',
        ]
    },
    {
        category: 'Arrows and chevrons',
        list: [
            'chevron-down',
            'chevron-left',
            'chevron-right',
            'chevron-up',
            'dot',
            'interpunct',
            'order-asc',
            'order-desc',
            'order-none',
        ]
    },
    {
        category: 'Add and remove',
        list: [
            'x',
            'checkmark',
            'plus',
            'minus',
            'checkmark-circle',
            'x-circle-filled',
            'plus-circle-filled',
            'minus-circle-filled',
            'checkmark-circle-filled',
        ]
    },
    {
        category: 'Attention',
        list: [
            'question-circle',
            'exclamation-circle',
            'information-circle',
            'exclamation-circle-filled',
            'information-circle-filled',
            'question-circle-small',
            'exclamation-circle-filled-small24',
            'information-circle-filled-small24',
        ]
    },
    {
        category: 'Links and medias',
        list: [
            'camera',
            'external-link',
            'file-pdf',
            'link',
        ]
    },
    {
        category: 'Rating',
        list: [
            'star-empty',
            'star-full',
            'star-half',
        ]
    },
    {
        category: 'Communication',
        list: [
            'actualite',
            'communaute',
            'email',
            'voice-command',
            'call-incoming',
            'call',
            'mobile-livechat',
            'chat',
        ]
    },
    {
        category: 'Time and place',
        list: [
            'clock',
            'calendar',
            'pin',
        ]
    },
    {
        category: 'Users',
        list: [
            'profile',
            'user-family',
            'user',
        ]
    },
    {
        category: 'Download and upload',
        list: [
            'download',
            'upload',
            'circle-download',
            'circle-upload',
        ]
    },
    {
        category: 'Social medias',
        list: [
            'facebook',
            'instagram',
            'youtube',
            'twitter',
        ]
    },
    {
        category: 'Cast and devices',
        list: [
            'appli-helix',
            'helix-tv',
            'relais-wifi',
            'mobile',
            'television',
        ]
    },
    {
        category: 'Account',
        list: [
            'account-balance',
            'installation',
            'support',
            'cart',
            'hierarchy',
        ]
    },
    {
        category: 'TV Plans',
        list: [
            'forfait-tv-fan-sports',
            'forfait-tv-la-decouverte',
            'forfait-tv-la-totale',
            'forfait-tv-le-fan-de-films-et-series',
            'forfait-tv-le-plein-la-vue',
            'forfait-tv-streaming',
        ]
    },
    {
        category: 'Services et options',
        list: [
            'helix-app',
            'tv-4k',
            'tv-forward',
            'tv-record',
            'casting',
            'cloud-dvr',
            'unlimited',
            'parental-control',
            'wifi',
            'world',
            'play-circle',
        ]
    },
    {
        category: 'Internet plans - options',
        list: [
            'helixinternet-jeuxvideos',
            'helixinternet-maison-connecte',
            'helixinternet-musique',
            'helixinternet-streaming',
            'helixinternet-wifi_ultime',
        ]
    },
    {
        category: 'Documentation',
        list: [
            'placeholder',
        ]
    }
];

export const illustrationIcons = [
    {
        category: 'Main',
        list: [
            'accessibility',
            'actuality',
            'agility',
            'apple',
            'application-client-area',
            'application-helix-tv',
            'applications',
            'availability-of-service',
            'bill',
            'business',
            'calendar',
            'call-me-back',
            'call-me-now',
            'canada',
            'cart',
            'check',
            'checklist',
            'chrono',
            'community',
            'contact-phone',
            'customer-service',
            'data',
            'delivery',
            'desinstallation',
            'differenciation',
            'email',
            'helix-mic',
            'hosting-data',
            'hosting',
            'information',
            'innovation',
            'installation',
            'instant-message',
            'instructions',
            'international',
            'invoice-deadline-48h',
            'moving-in',
            'my-account',
            'network-coverage-1',
            'network-coverage',
            'network-performance',
            'new-client',
            'notifications',
            'pause',
            'performance',
            'play',
            'point-of-sale',
            'pre-authorized-payment',
            'quebec',
            'question',
            'recycling',
            'replay',
            'search',
            'second-hand',
            'settings',
            'simultaneous-recordings',
            'smart-home',
            'sound-off',
            'sound-on',
            'store',
            'teamwork',
            'time',
            'travel',
            'trio-wifi',
            'troubleshooting',
            'united-states',
            'update',
            'user-1',
            'user-2',
            'user-3',
            'user-4',
            'verify-eligibility',
            'videotron-plus',
            'wifi',
        ]
    },
        {
        category: 'Options',
        list: [
            'casting',
            'cloud-dvr',
            'connection-reliable',
            'download-speed',
            'memory',
            'security',
            'student-discount',
            'subtitles',
            'unlimited',
            'upload-speed',
            'video-quality-4K',
            'video-quality-720p',
            'video-quality-1080p',
            'warranty-30-days',
        ]
    },
    {
        category: 'Options Mobility',
        list: [
            'water-resistance',
            'battery',
            'screen-size',
            'camera',
            'option-all-inclusive',
            'option-voicemail-email',
            'option-voicemail',
            'mobile-bundle-packages',
            'mobile-call-forwarding',
            'mobile-call-planning',
            'mobile-call-waiting',
            'mobile-conf-call',
            'mobile-display',
            'mobile-flex-cell',
            'mobile-international-calls',
            'mobile-large-format',
            'mobile-money-saving',
            'mobile-multiline',
            'mobile-protection',
            'mobile-unlimited',
            'mobile-voicemail-visual',
        ]
    },
    {
        category: 'Navigation',
        list: [
            'arrow-top',
            'arrow-bottom',
            'arrow-left',
            'arrow-right',
            'checkmark',
            'arrow-close',
            'size-reduce',
            'size-enlarge',
            'arrow-plus',
        ]
    },
    {
        category: 'Devices',
        list: [
            'bundle-1',
            'bundle-2',
            'bundle-3',
            'gateway-helix-1',
            'gateway-helix-2',
            'pod-relais-view-1',
            'pod-relais-view-2',
            'pod-relais-view-3',
            'remote',
            'terminal-remote',
            'terminal-top',
            'terminal',
            'card-memory',
            'card-sim',
            'television',
            'helix-tv-remote',
            'helix-tv',
            'internet-residential',
            'laptop-mobile',
            'multi-product',
            'mobility',
            'telephony-residential',
            'tablet-mobile-helix',
            'other-services',
        ]
    },
    {
        category: 'Forfait',
        list: [
            'forfait-le -plein-la-vue',
            'forfait-le-fan-de-sports',
            'forfait-la-decouverte',
            'forfait-la-totale',
            'forfait-le-fan-de-films-et-series',
            'forfait-le-leger',
        ]
    }
];

export const iconsPL = [
    // '_icon-font-awesome-stack',
    // '_icon-font-awesome',
    'arrow-to-bottom',
    'arrow-to-right--breadcrumb',
    'arrow-to-right',
    'arrow-to-top',
    'bullet-rating',
    'step-number',
    'svg-accessibility',
    'svg-app-store-fr',
    'svg-application-helix-stream',
    'svg-application-helix',
    'svg-arrow-circle-left',
    'svg-arrow-circle-right',
    'svg-arrow-sort-asc',
    'svg-arrow-sort-desc',
    'svg-arrow-sort',
    'svg-attention',
    'svg-boundary',
    'svg-business',
    'svg-calendar',
    'svg-call',
    'svg-cart-mini',
    'svg-cart',
    'svg-check-eligibility',
    'svg-checkbox-selected',
    'svg-checkmark-circle',
    'svg-checkmark',
    'svg-clock',
    'svg-cloud-dvr',
    'svg-collapse-trigger-arrow-down',
    'svg-collapse-trigger-arrow-up',
    'svg-device',
    'svg-download',
    'svg-edit',
    'svg-equipment',
    'svg-error',
    'svg-external-link',
    'svg-eye-dashed',
    'svg-eye',
    'svg-family',
    'svg-file-billing',
    'svg-filter',
    'svg-gateway',
    'svg-google-store-fr',
    'svg-handheld',
    'svg-handshake',
    'svg-helix-tv-app',
    'svg-helix-tv',
    'svg-helix',
    'svg-important',
    'svg-installation',
    'svg-internet',
    'svg-interrogation',
    'svg-letter',
    'svg-lightbulb',
    'svg-lock',
    'svg-logo-videotron',
    'svg-manage',
    'svg-mastercard',
    'svg-minus-bold',
    'svg-minus-circle',
    'svg-minus',
    'svg-move',
    'svg-other-services',
    'svg-parental-control',
    'svg-pdf',
    'svg-person',
    'svg-pin',
    'svg-plus-bold',
    'svg-plus-circle',
    'svg-plus',
    'svg-pod',
    'svg-reset',
    'svg-search',
    'svg-social',
    'svg-support',
    'svg-terminal-handheld',
    'svg-terminal',
    'svg-tpc',
    'svg-trash',
    'svg-travel',
    'svg-truck',
    'svg-tv',
    'svg-uninstallation',
    'svg-unlimited',
    'svg-upload',
    'svg-user-profile',
    'svg-video-play',
    'svg-voice-command',
    'svg-wifi',
    'svg-x',
    // 'svg',
];