

export const icons = [
    {
        category: 'Common controls',
        list: [
            'cancel',
            'out',
            'hourglass',
            'edit',
            'bin',
            'lock',
            'menu-burger',
            'menu-option',
            'repeat',
            'search',
            'settings',
            'eye-dash',
            'eye',
        ]
    },
    {
        category: 'Arrows and chevrons',
        list: [
            'chevron-down',
            'chevron-left',
            'chevron-right',
            'chevron-up',
            'dot',
            'interpunct',
            'order-asc',
            'order-desc',
            'order-none',
        ]
    },
    {
        category: 'Add and remove',
        list: [
            'x',
            'checkmark',
            'plus',
            'minus',
            'checkmark-circle',
            'x-circle--fill-color',
            'plus-circle-fill-color',
            'minus-circle-fill-color',
            'checkmark-circle-fill-color',
        ]
    },
    {
        category: 'Attention',
        list: [
            'question-circle',
            'exclamation-circle',
            'information-circle',
            'exclamation-circle-fill-color',
            'information-circle-fill-color',
            'question-circle-small',
            'exclamation-circle-fill-color-small24',
            'information-circle-fill-color-small24',
        ]
    },
    {
        category: 'Links and medias',
        list: [
            'camera',
            'external-link',
            'file-pdf',
            'link',
        ]
    },
    {
        category: 'Rating',
        list: [
            'star-empty',
            'star-full',
            'star-half',
        ]
    },
    {
        category: 'Communication',
        list: [
            'actualite',
            'communaute',
            'email',
            'voice-command',
            'call-incoming',
            'call',
            'mobile-livechat',
            'chat',
        ]
    },
    {
        category: 'Time and place',
        list: [
            'clock',
            'calendar',
            'pin',
        ]
    },
    {
        category: 'Users',
        list: [
            'profile',
            'user-family',
            'user',
        ]
    },
    {
        category: 'Download and upload',
        list: [
            'download',
            'upload',
            'circle-download',
            'circle-upload',
        ]
    },
    {
        category: 'Social medias',
        list: [
            'facebook',
            'instagram',
            'youtube',
            'twitter',
        ]
    },
    {
        category: 'Cast and devices',
        list: [
            'appli-helix',
            'helix-tv',
            'relais-wifi',
            'mobile',
            'television',
        ]
    },
    {
        category: 'Account',
        list: [
            'account-balance',
            'installation',
            'support',
            'cart',
            'hierarchy',
        ]
    },
    {
        category: 'TV Plans',
        list: [
            'forfait-tv-fan-sports',
            'forfait-tv-la-decouverte',
            'forfait-tv-la-totale',
            'forfait-tv-le-fan-de-films-et-series',
            'forfait-tv-le-plein-la-vue',
            'forfait-tv-streaming',
        ]
    },
    {
        category: 'Services et options',
        list: [
            'helix-app',
            'tv-4k',
            'tv-forward',
            'tv-record',
            'casting',
            'cloud-dvr',
            'unlimited',
            'parental-control',
            'wifi',
            'world',
            'play-circle',
        ]
    },
    {
        category: 'Internet plans - options',
        list: [
            'helixinternet-jeuxvideos',
            'helixinternet-maison-connecte',
            'helixinternet-musique',
            'helixinternet-streaming',
            'helixinternet-wifi_ultime',
        ]
    },
];

export const iconsPL = [
    // '_icon-font-awesome-stack',
    // '_icon-font-awesome',
    'arrow-to-bottom',
    'arrow-to-right--breadcrumb',
    'arrow-to-right',
    'arrow-to-top',
    'bullet-rating',
    'step-number',
    'svg-accessibility',
    'svg-app-store-fr',
    'svg-application-helix-stream',
    'svg-application-helix',
    'svg-arrow-circle-left',
    'svg-arrow-circle-right',
    'svg-arrow-sort-asc',
    'svg-arrow-sort-desc',
    'svg-arrow-sort',
    'svg-attention',
    'svg-boundary',
    'svg-business',
    'svg-calendar',
    'svg-call',
    'svg-cart-mini',
    'svg-cart',
    'svg-check-eligibility',
    'svg-checkbox-selected',
    'svg-checkmark-circle',
    'svg-checkmark',
    'svg-clock',
    'svg-cloud-dvr',
    'svg-collapse-trigger-arrow-down',
    'svg-collapse-trigger-arrow-up',
    'svg-device',
    'svg-download',
    'svg-edit',
    'svg-equipment',
    'svg-error',
    'svg-external-link',
    'svg-eye-dashed',
    'svg-eye',
    'svg-family',
    'svg-file-billing',
    'svg-filter',
    'svg-gateway',
    'svg-google-store-fr',
    'svg-handheld',
    'svg-handshake',
    'svg-helix-tv-app',
    'svg-helix-tv',
    'svg-helix',
    'svg-important',
    'svg-installation',
    'svg-internet',
    'svg-interrogation',
    'svg-letter',
    'svg-lightbulb',
    'svg-lock',
    'svg-logo-videotron',
    'svg-manage',
    'svg-mastercard',
    'svg-minus-bold',
    'svg-minus-circle',
    'svg-minus',
    'svg-move',
    'svg-other-services',
    'svg-parental-control',
    'svg-pdf',
    'svg-person',
    'svg-pin',
    'svg-plus-bold',
    'svg-plus-circle',
    'svg-plus',
    'svg-pod',
    'svg-reset',
    'svg-search',
    'svg-social',
    'svg-support',
    'svg-terminal-handheld',
    'svg-terminal',
    'svg-tpc',
    'svg-trash',
    'svg-travel',
    'svg-truck',
    'svg-tv',
    'svg-uninstallation',
    'svg-unlimited',
    'svg-upload',
    'svg-user-profile',
    'svg-video-play',
    'svg-voice-command',
    'svg-wifi',
    'svg-x',
    // 'svg',
];