const dataFilters = [
    {
        dataCheckboxes: {
            id: 'brand_filter_options',
            name: 'brand_filter_options',
            options: [
                {
                    id: 'brand_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
                {
                    id: 'brand_Samsung',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Samsung',
                    labelTypography: 'paragraph-default',
                    value: 'Samsung',
                },
                {
                    id: 'brand_Google',
                    isChecked: false,
                    isDisabled: false,
                    label: 'Google',
                    labelTypography: 'paragraph-default',
                    value: 'Google',
                },
                {
                    id: 'brand_Motorola',
                    isChecked: false,
                    isDisabled: false,
                    label: 'Motorola',
                    labelTypography: 'paragraph-default',
                    value: 'Motorola',
                },
                {
                    id: 'brand_TLC',
                    isChecked: false,
                    isDisabled: false,
                    label: 'TLC',
                    labelTypography: 'paragraph-default',
                    value: 'TLC',
                },
                {
                    id: 'brand_LG',
                    isChecked: false,
                    isDisabled: false,
                    label: 'LG',
                    labelTypography: 'paragraph-default',
                    value: 'LG',
                },
                {
                    id: 'brand_Alcatel',
                    isChecked: false,
                    isDisabled: true,
                    label: 'Alcatel',
                    labelTypography: 'paragraph-default',
                    value: 'Alcatel',
                },
            ],
        },
        id: 'brand_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Brand',
    },
    {
        dataCheckboxes: {
            id: 'capacity_filter_options',
            name: 'capacity_filter_options',
            options: [
                {
                    id: 'capacity_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'capacity_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Capacity',
    },
    {
        dataSlider: {
            max: {
                description: '$999/month',
                inputId: 'inputIdMax',
                legend: 'Maximum',
                value: 999,
            },
            min: {
                description: '$0/month',
                inputId: 'inputIdMin',
                legend: 'Minimum',
                value: 0,
            },
            minimumGap: 20,
            step: 1,
            unitLabel: '$',
            unitPosition: 'start',
            value: [0, 999],
        },
        id: 'monthly_price_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Monthly price',
    },
    {
        dataCheckboxes: {
            id: 'color_filter_options',
            name: 'color_filter_options',
            options: [
                {
                    id: 'color_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'color_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Color',
    },
    {
        dataCheckboxes: {
            id: 'promotions_filter_options',
            name: 'promotions_filter_options',
            options: [
                {
                    id: 'promotions_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'promotions_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Promotions',
    },
    {
        dataCheckboxes: {
            id: 'availability_filter_options',
            name: 'availability_filter_options',
            options: [
                {
                    id: 'availability_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'availability_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Availability',
    },
    {
        dataCheckboxes: {
            id: 'os_filter_options',
            name: 'os_filter_options',
            options: [
                {
                    id: 'os_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'os_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'Operating Systems',
    },
    {
        dataCheckboxes: {
            id: 'state_filter_options',
            name: 'state_filter_options',
            options: [
                {
                    id: 'state_Apple',
                    isChecked: true,
                    isDisabled: false,
                    label: 'Apple',
                    labelTypography: 'paragraph-default',
                    value: 'Apple',
                },
            ],
        },
        id: 'state_filter',
        isDisabled: false,
        isExpandedByDefault: true,
        title: 'State',
    },
];
