export const chipsData = [
    {
        deleteButton: "alert('You clicked on the delete button for the -Apple- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Apple',
        isDisabled: false,
        label: 'Apple',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -128 Go- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_128Go',
        isDisabled: true,
        label: '128 Go',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -256 Go- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_256Go',
        isDisabled: true,
        label: '256 Go',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Samsung- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Samsung',
        isDisabled: false,
        label: 'Samsung',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Black- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Black',
        isDisabled: false,
        label: 'Black',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -White- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_White',
        isDisabled: false,
        label: 'White',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Blue- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Blue',
        isDisabled: false,
        label: 'Blue',
    },
];

export const chipsWithTwigBlock = [
    {
        deleteButton: "alert('You clicked on the delete button for the -Google- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Google',
        isDisabled: true,
        label: 'Google',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -64 Go- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_64Go',
        isDisabled: false,
        label: '64 Go',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -512 Go- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_512Go',
        isDisabled: false,
        label: '512 Go',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -LG- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_LG',
        isDisabled: true,
        label: 'LG',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Black- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Black',
        isDisabled: false,
        label: 'Black',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Gold- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Gold',
        isDisabled: false,
        label: 'Gold',
    },
    {
        deleteButton: "alert('You clicked on the delete button for the -Green- chip.')",
        deleteButtonAriaLabel: 'On a click, it will open en alert box.',
        id: 'chip_Green',
        isDisabled: false,
        label: 'Green',
    },
];
